export { Landing } from './Landing';
export { Submit } from './Submit';
export { Payment } from './Payment';
export { Status } from './Status';
export { Login } from './Login';
export { Register } from './Register';
export { Dashboard } from './Dashboard';
export { DashboardInProgress } from './DashboardInProgress';
export { DashboardCompleted } from './DashboardCompleted';
